source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SMTagField_Example', :exclusive => true do
  pod "SMTagField", :path => "../"
end

target 'SMTagField_Tests', :exclusive => true do
  pod "SMTagField", :path => "../"

  
end
